### ISSUE TITLE
no module 'binance.futures' found

### ISSUE THREAD

**Issue by alterdaemon** [aps32221/binance_webhook_Fastapi#1]
binance_webhook_fastapi/main.py", line 6, in <module>
    from binance.futures import Futures
ModuleNotFoundError: No module named 'binance.futures'

**Comment by aps32221** [comment]
Could you please check the dependencies are installed correctly?
It’s working fine for me.

**Comment by alterdaemon** [comment]
Hi, yes, I double checked that and everything is installed and available, I use conda and virtual env for that.
those imports relates to binance-futures-connector library?

**Comment by aps32221** [comment]
Sorry for not getting back to you sooner.
Yes.
I've recreated the new environment and got the same error.
It seems the Binance future APIs are been renamed, we need to change "Futures" to "CMFutures".
I'll fix it later, or feel free to submit PR.

**Comment by aps32221** [comment]
fix by [ad614a5](https://github.com/aps32221/binance_webhook_Fastapi/commit/ad614a596c0cf3a30a61697524b2948b236e6ded)

**Comment by alterdaemon** [comment]
Thank you for the quick fix. Going to test it now.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent from Proton Mail mobile

-------- Original Message --------
