### ISSUE TITLE
proper TradingView alert definition example (current one gives validation error)

### ISSUE THREAD

**Issue by alterdaemon** [aps32221/binance_webhook_Fastapi#2]
{
  "passphrase": "dbA5KD6PpmINEqKOFx3vJDAQy1YIHWR",
  "time": "{{timenow}}",
  "exchange": "{{exchange}}",
  "ticker": "{{ticker}}",
  "bar": {
      "time": "{{time}}",
      "open": "{{open}}",
      "high": "{{high}}",
      "low": "{{low}}",
      "close": "{{close}}",
      "volume": "{{volume}}"
  },
  "strategy": {
      "position_size": "{{strategy.position_size}}",
      "order_action": "{{strategy.order.action}}",
      "order_contracts": "{{strategy.order.contracts}}",
      "order_price": "{{strategy.order.price}}",
      "order_id": "{{strategy.order.id}}",
      "market_position": "{{strategy.market_position}}",
      "market_position_size": "{{strategy.market_position_size}}",
      "prev_market_position": "{{strategy.prev_market_position}}",
      "prev_market_position_size": "{{strategy.prev_market_position_size}}"
  }
}

**Comment by aps32221** [comment]
you can find it here:
https://github.com/aps32221/binance_webhook_Fastapi/blob/ad614a596c0cf3a30a61697524b2948b236e6ded/main.py#L39-L65

Please make sure that all the properties type matches the data type above.
And here is the sample that works for me:
{
"passphrase": "random_phrase",
"time": "{{timenow}}",
"exchange": "{{exchange}}",
"ticker": "ETHUSDT",
"bar": {
"time": "{{time}}",
"open": "0.0",
"high": "0.0",
"low": "0.0",
"close": "0.0",
"volume": "0.0"
},
"strategy": {
"position_size": "0.0",
"order_action": "sell",
"order_contracts": "0.01",
"order_price": "0.0",
"order_id": "{{strategy.order.id}}",
"market_position": "0.0",
"market_position_size": "0.0",
"prev_market_position": "{{strategy.prev_market_position}}",
"prev_market_position_size": "0.0"
}
}
BTW if you use the USD-M Futures like me, you should change all CMFutures to UMFutures
https://github.com/aps32221/binance_webhook_Fastapi/blob/ad614a596c0cf3a30a61697524b2948b236e6ded/main.py#L6-L18

**Comment by alterdaemon** [comment]
thx for the tip regarding UMFutures, It works perfectly now!
thinking about setting some Telegram alerts on the signal but it's another story.
